name: 'Prompt Action'
description: 'Prompt AI about... well, anything!'
author: 'FidelusAleksander'
branding:
  icon: message-circle
  color: blue
inputs:
  token:
    description: >
      Personal access token, can be passed as secrets.GITHUB_TOKEN
    default: ${{ github.token }}
  prompt:
    description: >
      What do you want to ask?
    required: false
  prompt-file:
    description: >
      Path to a file containing the prompt
    required: false
  model:
    description: >
      The AI model to use for generating the response
    default: 'gpt-4o'
  system-prompt:
    description: >
      System prompt to provide context for the AI
    required: false
  system-prompt-file:
    description: >
      Path to a file containing the system prompt
    required: false
  response-schema-file:
    description: >
      Path to a JSON file containing the response schema for structured outputs
    required: false
outputs:
  text:
    description: >
      The answer to your question
runs:
  using: 'node20'
  main: 'dist/index.js'
