name: "Ask AI"
description: "Ask AI about ... well, anything!"
author: "FidelusAleksander"
inputs:
  github-token:
    description: >
      Personal access token, can be `${{ secrets.GITHUB_TOKEN }}`
    default: ${{ github.token }}
  prompt:
    description: >
      What do you want to ask?
    required: true
outputs:
  text:
    description: >
      The answer to your question
runs:
  using: "node16"
  main: "dist/index.js"
