name: Run Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  models: read

jobs:
  test-action-prompt:
    name: Test Action with Prompt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test action
        id: test
        uses: ./
        with:
          prompt: "What is the meaning of life?"

  test-action-prompt-file:
    name: Test Action with Prompt File
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test action
        uses: ./
        with:
          prompt-file: ".github/prompts/ai.md"

  test-typescript:
    name: TypeScript Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - run: npm test
